### ISSUE TITLE
Actionsの`github pages`で`out/`以下に`npx next export`によって生成された静的ページ（？）を見れるようにしたいが、なぜかReadme.mdが表示されてしまう。

### ISSUE THREAD

**Issue by lemolatoon** [lemolatoon/NextJsPractice#1]
[言及しているページ](https://lemolatoon.github.io/NextJsPractice/)
[`.github/workflows/github-pages.yml`](https://github.com/lemolatoon/NextJsPractice/blob/main/.github/workflows/github-pages.yml) at a620b6f0c1107213388e18e373e4fc9313d08acf
```yaml
name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: setup dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: export
        run: npm run export

      - name: add nojekyll
        run: touch ./out/.nojekyll

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./out
```
